//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.Rpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpiControl
    {
        public int Id { get; set; }
        public string DtSchedule { get; set; }
        public string Data { get; set; }
        public int RpiDeviceId { get; set; }
    
        public virtual RpiDevice RpiDevice { get; set; }
    }
}
