//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.Rpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpiComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RpiComponent()
        {
            this.RpiVersionMaps = new HashSet<RpiVersionMap>();
        }
    
        public int Id { get; set; }
        public string ComponentName { get; set; }
        public string Description { get; set; }
        public int RpiDataTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RpiVersionMap> RpiVersionMaps { get; set; }
        public virtual RpiDataType RpiDataType { get; set; }
    }
}
