//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.Rpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpiDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RpiDevice()
        {
            this.RpiDatalogs = new HashSet<RpiDatalog>();
            this.RpiControls = new HashSet<RpiControl>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int RpiVersionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RpiDatalog> RpiDatalogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RpiControl> RpiControls { get; set; }
        public virtual RpiVersion RpiVersion { get; set; }
    }
}
