//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.Rpi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RpiDBContainer1 : DbContext
    {
        public RpiDBContainer1()
            : base("name=RpiDBContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RpiDevice> RpiDevices { get; set; }
        public virtual DbSet<RpiDatalog> RpiDatalogs { get; set; }
        public virtual DbSet<RpiControl> RpiControls { get; set; }
        public virtual DbSet<RpiVersion> RpiVersions { get; set; }
        public virtual DbSet<RpiVersionMap> RpiVersionMaps { get; set; }
        public virtual DbSet<RpiComponent> RpiComponents { get; set; }
        public virtual DbSet<RpiDataType> RpiDataTypes { get; set; }
    }
}
