//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.v10.Areas.Rpi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpiVersionMap
    {
        public int Id { get; set; }
        public string NameMap { get; set; }
        public string PinNo { get; set; }
        public int RpiComponentId { get; set; }
        public int RpiVersionId { get; set; }
    
        public virtual RpiComponent RpiComponent { get; set; }
        public virtual RpiVersion RpiVersion { get; set; }
    }
}
